steps:
 - id: install_packages
   name: 'gcr.io/cloud-builders/npm:node-12.18.3'
   args:
   - 'install'
 - id: prerender_browser_files
   name: 'gcr.io/cloud-builders/npm:node-12.18.3'
   entrypoint: 'bash'
   args:
    - '-c'
    - |-
      npm run build --prod
   waitFor:
   - install_packages
 - id: 'Build docker image angular'
   name: 'gcr.io/cloud-builders/docker'
   args: ["build", 
    "-t", 
    "gcr.io/$PROJECT_ID/basketball-pro-ipad:$BUILD_ID", "."]

 - id: 'Push docker image angular'
   name: 'gcr.io/cloud-builders/docker'
   args: ["push",  "gcr.io/$PROJECT_ID/basketball-pro-ipad:$BUILD_ID"]

 - id: 'Create or update run services'
   name: 'gcr.io/cloud-builders/gcloud'
   args:
      - 'run'
      - 'deploy'
      - 'ui-basketball-pro-ipad'
      - '--image'
      - 'gcr.io/$PROJECT_ID/basketball-pro-ipad:$BUILD_ID'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
